channels:
- conda-forge
- damianavila82
- defaults
dependencies:
- rise
- numpy
- cython
- pip:
  - autograd
  - matplotlib
  - numpy
  - sympy
  - ipywidgets
  - scipy
  - numba
  - pydoe
  - pandas
  - ttpy

